// Generated by BiocJobs 0.99.0 from the 'read-10x-counts' job declared in
// Bioconductor package DropletUtils (inst/biocjobs/). Do not edit;
// regenerate with: Rscript -e 'BiocJobs::biocjobsCLI()' nextflow <pkg> read-10x-counts

process READ_10X_COUNTS {
    tag "${meta.id}"
    container 'ghcr.io/kevinrue/dropletutils:devel'
    cpus 1
    memory '4 GB'
    disk '10 GB'

    input:
    // meta: map identifying the unit of work; meta.id names the tag
    // mtx_file: Raw count matrix (mtx)
    // barcodes_file: Cell barcodes (tsv)
    // genes_file: Feature annotations (tsv)
    tuple val(meta), path(mtx_file), path(barcodes_file), path(genes_file)
    // Sample name (string; required)
    val sample_name

    output:
    tuple val(meta), path('outfile.loom'), emit: outfile

    script:
    """
    Rscript -e 'BiocJobs::execJob("DropletUtils", "read-10x-counts")' \\
        --mtx_file '${(mtx_file as String).replace("'", "'\\''")}' \\
        --barcodes_file '${(barcodes_file as String).replace("'", "'\\''")}' \\
        --genes_file '${(genes_file as String).replace("'", "'\\''")}' \\
        --sample_name '${(sample_name as String).replace("'", "'\\''")}' \\
        --outfile 'outfile.loom'
    """

    stub:
    """
    touch 'outfile.loom'
    """
}
