// Generated by BiocJobs 0.99.0 from the 'read-10x-counts' job declared in
// Bioconductor package DropletUtils (inst/biocjobs/). Do not edit;
// regenerate with: Rscript -e 'BiocJobs::biocjobsCLI()' nextflow <pkg> read-10x-counts

process READ_10X_COUNTS {
    tag "read-10x-counts"
    container 'bioconductor/bioconductor_docker:RELEASE_3_23'
    cpus 1
    memory '4 GB'
    disk '10 GB'

    input:
    // Raw count matrix (mtx)
    path mtx_file
    // Cell barcodes (tsv)
    path barcodes_file
    // Feature annotations (tsv)
    path genes_file
    // Sample name (string; required)
    val sample_name

    output:
    path 'outfile.loom', emit: outfile

    script:
    """
    Rscript -e 'BiocJobs::execJob("DropletUtils", "read-10x-counts")' \\
        --mtx_file '${(mtx_file as String).replace("'", "'\\''")}' \\
        --barcodes_file '${(barcodes_file as String).replace("'", "'\\''")}' \\
        --genes_file '${(genes_file as String).replace("'", "'\\''")}' \\
        --sample_name '${(sample_name as String).replace("'", "'\\''")}' \\
        --outfile 'outfile.loom'
    """

    stub:
    """
    touch 'outfile.loom'
    """
}
